### ISSUE TITLE
Vulnerabilities reported by npm audit

### ISSUE THREAD

**Issue by cmmv91** [zephyrdeveloper/zapi_nodejs#2]
Found the vulnerabilities shown below, please fix.
Using:
Node v10.12.0
npm 6.4.1

<img width="563" alt="screen shot 2018-10-17 at 5 00 32 pm" src="https://user-images.githubusercontent.com/37762156/47115943-2e2f9900-d22e-11e8-9251-b924ef222970.png">

**Comment by masudjbd** [comment]
Hi cmmv91 ,
Fixed.
